[package]
name = "spl-token-wrap"
version = "0.1.0"
description = "Solana Program Library Token Wrap"
authors = ["Solana Maintainers <maintainers@solana.foundation>"]
repository = "https://github.com/solana-labs/solana-program-library"
license = "Apache-2.0"
edition = "2018"

[features]
no-entrypoint = []
test-sbf = []

[dependencies]
bincode = "1.3.3"
borsh = "0.1"
bytemuck = { version = "1.14.0", features = ["derive"] }
mpl-token-metadata = "4.0.0"
num_enum = "0.7"
remove = "0.1.3"
serde = {version = "1.0.195", features = ["derive"] }
solana-program = "1.17.6"
solana-program-test = "1.17.14"
solana-sdk = "1.17.15"
spl-associated-token-account = { version = "2.0", path = "../../associated-token-account/program", features = ["no-entrypoint"] }
spl-token = { version = "4.0", path = "../../token/program", features = ["no-entrypoint"] }
spl-token-2022 = { version = "1.0", path = "../../token/program-2022", features = ["no-entrypoint"] }
thiserror = "1.0"

[lib]
crate-type = ["cdylib", "lib"]
