on:
  push:
    branches:
      - master
  issues:
    types: [labeled]
  issue_comment:
    types: [created]
  pull_request_target:
    types: [labeled]

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  autopr:
    runs-on: self-hosted
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        ref: main
        fetch-depth: 1
    - name: AutoPR
      uses: irgolic/AutoPR@main
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        base_branch: main
